# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8487215ee0e5a4116cb0e6c9d3783bacd3f82f23e92db602af52c87aa8407693587818f5d669895dcafc16285116702245703220457eac32c44128be8d0a6fc0

test:
  secret_key_base: f2e0fc340121a38f1dfe6c7bb85aa15e34f707d8fcd20423d4452384aaf61231fc36b7cae010bb67ab1209a0310a91068a01161e57c2e37a9dbc409d3c47e979

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
